name: tlu_students
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  win32: ^5.13.0
  win32_registry: ^1.1.5
  flutter_bloc: ^9.1.1
  get_it: ^8.3.0
  shared_preferences: ^2.5.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.0
  equatable: ^2.0.8
  intl: ^0.19.0
  geolocator: ^11.1.0
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  google_mlkit_face_detection: ^0.13.1
  flutter_plugin_android_lifecycle: ^2.0.21
  camera: ^0.11.0+2
  custom_clippers: ^2.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3
  webview_flutter: ^4.8.0
  toastification: ^2.3.0
  network_info_plus: ^6.0.0
  dio: ^5.9.2
  signal_strength_indicator: ^0.4.1
  socket_io_client: ^3.0.2
  dynamic_height_grid_view: ^0.0.4
  fl_chart: ^0.66.2
  circular_seek_bar: ^1.1.1
  connectivity_plus: ^6.1.5
  collection: ^1.19.1
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.4
  badges: ^3.2.0
  device_info_plus: ^10.1.2
  flutter_markdown: ^0.7.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

# PHẦN QUAN TRỌNG NHẤT: Ép các plugin đời cũ cập nhật theo Flutter 3.29.1
dependency_overrides:
  # Bản 2.0.21 đủ mới để fix lỗi Registrar nhưng vẫn chạy được trên Dart 3.7
  flutter_plugin_android_lifecycle: 2.0.21
  # Hạ từ 2.2.23 xuống bản thấp hơn một chút (ví dụ 2.2.10) để phù hợp với Dart 3.7
  path_provider_android: 2.2.10
  webview_flutter_android: 3.16.8

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
  fonts:
    enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100